<Project Sdk="Microsoft.NET.Sdk">
 <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWindowsForms>true</UseWindowsForms><ImplicitUsings>enable</ImplicitUsings></PropertyGroup>
 <ItemGroup><Compile Include="../../src/BambooKarambaBridge/Input.cs" Link="Input.cs"/></ItemGroup>
</Project>
