<Project Sdk="Microsoft.NET.Sdk">
 <PropertyGroup><TargetFramework>net8.0-windows</TargetFramework><UseWindowsForms>true</UseWindowsForms><EnableDefaultCompileItems>false</EnableDefaultCompileItems><DefineConstants>COMPILE_CHECK</DefineConstants></PropertyGroup>
 <ItemGroup><Compile Include="02_Module.compile.cs"/></ItemGroup>
</Project>
